DB_USERNAME: sa
DB_PASSWORD: sa
DB_HOST: oracle-free
DB_PORT: 1521
DB_NAME: Z

ISSUER_URI: https://sa-api.supersurvey.live
#AUTHORIZATION_URI: http://localhost:9090/oauth2/authorize
#TOKEN_URI: http://localhost:9090/oauth2/token
#USER_INFO_URI: http://localhost:9090/oauth2/userinfo
#REDIRECT_URI: http://localhost:8000/login/oauth2/code/admin

SEND_REDIRECT_URI: https://supersurvey.live/user
REDIRECT_URI: https://sa-api.supersurvey.live/login/oauth2/code/google
POST_LOGOUT_REDIRECT_URI: https://sa-api.supersurvey.live

#ACT_PRIVATE: access-refresh-token-keys/access-token-private.key
#ACT_PUBLIC: access-refresh-token-keys/access-token-public.key
## This is for the refresh token
#RET_PRIVATE: access-refresh-token-keys/refresh-token-private.key
#RET_PUBLIC: access-refresh-token-keys/refresh-token-public.key

#MAIL_USERNAME: sokname56@gmail.com
#MAIL_PASSWORD: tcps zgvu rnsf klrf
MAIL_USERNAME: p.soknaem@gmail.com
MAIL_PASSWORD: royr ysoq gfae omeq
MAIL_HOST: smtp.gmail.com
MAIL_HOST_PORT: 587

#minio
#minio-url: http://sa_online_survey_api-minio1-1:9000
minio-url: http://35.234.48.245:9000
minio-bucket: sa-resource
MINIO_SECRETE_KEY: minio123
MINIO_ACCESS_KEY: minio
#media
base-uri: https://resource.supersurvey.live
image-endpoint: /api/v1/files
video-endpoint: /api/v1/files
survey-share-url: http://localhost:3000/response/
survey-share-url-prod: https://supersurvey.live/response/
survey-base-url: https://supersurvey.live

logo-path: static/images/logo.png